### PR TITLE
Car Tweaks

### PR DESCRIPTION
**Pull request by larsll**
*Issue #, if available:*

*Description of changes:*
These fixes will make the following changes to the cars:
* DREM optimizes the Tensorflow models to OpenVINO; this patch will now enable the car to take benefit, reducing model load times down to 1-2 seconds. This patch is equal to https://github.com/aws-deepracer/aws-deepracer-model-optimizer-pkg/pull/2 and builds on https://github.com/aws-solutions-library-samples/guidance-for-aws-deepracer-event-management/pull/9.
* A small CSS change prevents the UI to zoom in on a double-click on touch-screens.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by larsll** [comment]
@marcobuss @esbjj @StevenAskwith I would strongly suggest to merge this in before re:Invent; the model load times will simplify life a lot, and enable more efficient model changes during 2 minute runs.

**Comment by StevenAskwith** [comment]
@larsll most of the team in on holiday this week, will review next week, but the idea looks good!

**Comment by MarkRoss-Eviden** [comment]
Hi @StevenAskwith FYI as part of clarification questions for the finals we've asked if this functionality will be available.  As you can imagine with limited practice (2 hour slot for 16 competitors on the Tues and Weds before round 1) and the limited time per racer in all rounds (2 min attempts) it's quite material whether changing models mid run takes ~45s or 2s.

**Comment by StevenAskwith** [comment]
@MarkRoss-Eviden I triggered the deploy to my test environment ~30 mins ago, will update after I've tested.

**Review by StevenAskwith — APPROVED** [review]

**Pull request merged**
